<?php

/**
 * Class ColocarDatosCommand
 * @author Me
 */
class ColocarDatosCommand extends CConsoleCommand
{
    public function run($args)
    {
        $usersSQL = "SELECT id FROM {{users}} WHERE username = :name";
        $builder = new CDbCommandBuilder(Yii::app()->db->schema);
        $idCommand = $builder->createSqlCommand($usersSQL,array(
            'name' => 'admin'
        ));
        list($idUser) = array_values($idCommand->queryRow()); //NOTE Importante
        $command = $builder->createMultipleInsertCommand("{{Tipoencuesta}}",array(
            array(
                'enunciado' => "Guión de entrevista para universidades, institutos tecnológicos, escuelas técnicas",
                'identificador' => 'tipoencuesta_uni',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => "Guión de entrevista para institutos, centros, grupos, laboratorios, otros",
                'identificador' => 'tipoencuesta_otros',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
        ));
        $command = $builder->createMultipleInsertCommand("{{Pregunta}}",array(
            //IMPORTANTE Grupo 1 de INSTRUMENTO IUTET
            array(
                'enunciado' => 'Nombre del entrevistado',
                'identificador' => 'preg_nom_entr',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Universidades, institutos tecnológicos, escuelas técnicas',
                'identificador' => 'preg_universidad_pertenece',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Año de fundación',
                'identificador' => 'preg_ano_fundacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Ubicación',
                'identificador' => 'preg_universidad_ubicacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Municipio',
                'identificador' => 'preg_municipio',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Caracter',
                'identificador' => 'preg_caracterpublicoprivado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            //FIN DE GRUPO 1
            //COMIENZO DE GRUPO 2
            array(
                'enunciado' => 'Número de nucleos y sedes',
                'identificador' => 'preg_sedenucleo_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Sede / Núcleo',
                'identificador' => 'preg_sedenucleo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Ubicación',
                'identificador' => 'preg_sedenucleo_ubicacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            //FIN DE GRUPO 2
            //COMIENZO DE GRUPO 3 
            array(
                'enunciado' => 'Actividades de ciencia, tecnología e innovación que se desarrollan en  las universidades, institutos tecnológicos, escuelas técnicas, según el artículo 27 de la LOCTI',
                'identificador' => 'preg_actividadesciencia_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Si/No',
                'identificador' => 'preg_actividadesciencia_sino',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuales?',
                'identificador' => 'preg_actividadesciencia_cuales',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ), 
            // FIN DE GRUPO 3
            // COMIENZO DE GRUPO 4
            array(
                'enunciado' => 'Talento Humano en Ciencia, Tecnología e Innovación de la universidad/institutos tecnológicos/escuelas técnicas/otros',
                'identificador' => 'preg_talentohumano_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nombre',
                'identificador' => 'preg_talentohumano_nombre',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Edad',
                'identificador' => 'preg_talentohumano_edad',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nivel Académico',
                'identificador' => 'preg_talentohumano_nivelac',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Universidad en que cursó estudios',
                'identificador' => 'preg_talentohumano_uni_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nacional pública',
                'identificador' => 'preg_talentohumano_nacionalpub',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nacional privada',
                'identificador' => 'preg_talentohumano_nacionalpri',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Internacional',
                'identificador' => 'preg_talentohumano_internacional',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ),        
            array(
                'enunciado' => 'Fuente de financiamiento de estudios',
                'identificador' => 'preg_talentohumano_fuentefin',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Categoría PEII',
                'identificador' => 'preg_talentohumano_categoriapeii',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Investigador',
                'identificador' => 'preg_talentohumano_pei_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Innovador',
                'identificador' => 'preg_talentohumano_pei_inn',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de Experiencia',
                'identificador' => 'preg_talentohumano_exp_area',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Linea de investigación',
                'identificador' => 'preg_talentohumano_linea_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ),
            //Fin del grupo  4
            //Comienzo del grupo 5
            array(
                'enunciado' => 'Numero de egresados de programas de doctorado en los últimos 12 años',
                'identificador' => 'preg_doctorado_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de doctorado existentes',
                'identificador' => 'preg_doctorado_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_doctorado_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 5
            //Comienzo del grupo 6
            array(
                'enunciado' => 'Numero de egresados de programas de maestria en los últimos 12 años',
                'identificador' => 'preg_maestria_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de maestria existentes',
                'identificador' => 'preg_maestria_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_maestria_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 6
            //Comienzo del grupo 7
            array(
                'enunciado' => 'Numero de egresados de programas de especialidades en los últimos 12 años',
                'identificador' => 'preg_especialidades_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de especialidades existentes',
                'identificador' => 'preg_especialidades_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_especialidades_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 7
            //Comienzo del grupo 8
            array(
                'enunciado' => 'Numero de egresados de programas de pregrado en los últimos 12 años',
                'identificador' => 'preg_pregrado_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de pregrado existentes',
                'identificador' => 'preg_pregrado_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_pregrado_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 8
            //Comienzo del grupo 9
            array(
                'enunciado' => 'Proyectos aprobados y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_proyectosaprob_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Proyectos aprobados y financiados',
                'identificador' => 'preg_proyectosaprob_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de proyectos aprobados',
                'identificador' => 'preg_proyectosaprob_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 9
            //Comienzo del grupo 10
            array(
                'enunciado' => 'Recursos aprobados y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_recursosaprob_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Recursos aprobados y financiados',
                'identificador' => 'preg_recursosaprob_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de recursos aprobados',
                'identificador' => 'preg_recursosaprob_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 10
            //Comienzo del grupo 11
            array(
                'enunciado' => 'Proyectos aprobados por área y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_proyectosaprob_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de concentración',
                'identificador' => 'preg_proyectosaprob_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de proyectos aprobados por área',
                'identificador' => 'preg_proyectosaprob_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 11
            //Comienzo del grupo 12
            array(
                'enunciado' => 'Recursos aprobados y financiados por área en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_recursosaprob_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de concentración',
                'identificador' => 'preg_recursosaprob_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Recursos aprobados',
                'identificador' => 'preg_recursosaprob_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 12
            //Comienzo del grupo 13
            array(
                'enunciado' => 'Producción Tecnológica (Patentes) en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por área de especialización',
                'identificador' => 'preg_patentes_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de especialización',
                'identificador' => 'preg_patentes_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Total de producción tecnológica (Patentes)',
                'identificador' => 'preg_patentes_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 13
            //Comienzo del grupo 14
            array(
                'enunciado' => 'Mencione patentes',
                'identificador' => 'preg_patentes_mencionar_pat',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ), 
            // Fin del grupo 14
            //Comienzo del grupo 15
            array(
                'enunciado' => 'Revistas arbitradas e indexadas y número de publicaciones por área de especialización que tienen  la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12',
                'identificador' => 'preg_revistas_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de especialización',
                'identificador' => 'preg_revistas_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Revista',
                'identificador' => 'preg_revistas_area_revista',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Total de publicaciones',
                'identificador' => 'preg_revistas_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 15
            //Comienzo del grupo 16
            array(
                'enunciado' => 'Líneas de Investigación existentes en la universidad/institutos tecnológicos/escuelas técnicas/otros ',
                'identificador' => 'preg_lineas_inv_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Líneas de Investigación',
                'identificador' => 'preg_lineas_inv_lineasinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Ejes Temáticos',
                'identificador' => 'preg_lineas_inv_ejestematico',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programa de Postgrado de adscripción',
                'identificador' => 'preg_lineas_inv_programapost',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            //Fin del grupo 16
            //Comienzo del grupo 17
            array(
                'enunciado' => 'Actores participantes en la ejecución de proyectos de ciencia y tecnología generados en la universidad/institutos tecnológicos/escuelas técnicas/otros',
                'identificador' => 'preg_actores_fin_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Actores participantes en la ejecución de proyectos',
                'identificador' => 'preg_actores_fin_actorespart',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Actores de financiamiento en la ejecución de proyectos',
                'identificador' => 'preg_actores_fin_actoresfin',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            // Fin del grupo 17
            //Comienzo del grupo 18
            array(
                'enunciado' => 'Pertenecen a alguna Red Temáticas de cooperación',
                'identificador' => 'preg_red_tem_pert',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Mencione',
                'identificador' => 'preg_red_tem_mencione',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            //Fin del grupo 18
            //Comienzo del grupo 19
            array(
                'enunciado' => 'Cuál es la problemática que se presenta en la universidad/institutos tecnológicos/escuelas técnicas/otros?',
                'identificador' => 'preg_problematica_cual',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Describa',
                'identificador' => 'preg_problematica_describa',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            // Fin del grupo 19
            // Comienzo del grupo 20
            array(
                'enunciado' => 'Infraestructura en ciencia, tecnología e innovación existente',
                'identificador' => 'preg_infraestructura_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Se encuentra Activa',
                'identificador' => 'preg_infraestructura_activa',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Condiciones de espacios',
                'identificador' => 'preg_infraestructura_espacios',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Equipamiento',
                'identificador' => 'preg_infraestructura_equipamiento',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Uso de la infraestructura',
                'identificador' => 'preg_infraestructura_usoinf_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Docencia',
                'identificador' => 'preg_infraestructura_usodoc',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Investigacion',
                'identificador' => 'preg_infraestructura_usoinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            //Fin del grupo 20
            //Comienzo del grupo 21
            array(
                'enunciado' => '¿Actualmente tiene servicio de internet?',
                'identificador' => 'preg_internet_servint',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Proveedor de internet',
                'identificador' => 'preg_internet_proveedorint',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual proveedor?',
                'identificador' => 'preg_internet_cualprov',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Nivel de satisfacción del servicio?',
                'identificador' => 'preg_internet_usoinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            // Fin del grupo 21
            // Comienzo grupo 22 
            array(
                'enunciado' => '¿Cuenta su Organización con un Comité de Ética qué evalúe, controle y conozca  los protocolos de investigación, experimentación y resultados que son presentados al público?',
                'identificador' => 'preg_comiteetica_evalue',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual comité?',
                'identificador' => 'preg_comiteetica_cual',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            // Fin del grupo 22
            // Comienzo del grupo 23
            array(
                'enunciado' =>'¿Cómo está compuesto? (para cada integrante, por favor señalar: Identificación, profesión, cargo, correo).?\n Nota: Si usted no tiene comité de Ética deje en blanco',
                'identificador' => 'preg_comiteetica2_composicion_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Identificación',
                'identificador' => 'preg_comiteetica2_ident',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Profesión',
                'identificador' => 'preg_comiteetica2_profesion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Cargo',
                'identificador' => 'preg_comiteetica2_cargo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Correo',
                'identificador' => 'preg_comiteetica2_correo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            // Fin del grupo 23
            // Comienzo del grupo 24 
            array(
                'enunciado' => '¿En qué fecha y a través de qué resolución (administrativa, legal) fue creado?',
                'identificador' => 'preg_comiteetica3_fecha',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Dispone de actas de las reuniones que realiza?',
                'identificador' => 'preg_comiteetica3_reuniones',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuántos trabajos científicos han evaluado en los últimos cinco años?',
                'identificador' => 'preg_comiteetica3_trabev',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Mencione titulos por favor',
                'identificador' => 'preg_comiteetica3_titulosmenc',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuáles han sido las principales dificultades que ha encontrado en su funcionamiento?',
                'identificador' => 'preg_comiteetica3_principalesdif',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Si no dispone de un Comité de Ética, ¿de qué forma se evalúa y/o controla las investigaciones, proyectos?',
                'identificador' => 'preg_comiteetica3_formaev',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Tiene conocimiento y vínculos con otras entidades que evalúen éticamente investigaciones científicas (Universidades, Comités de Ética autónomos, instituciones públicas y/o privadas de financiamiento de proyectos, etc.)?.',
                'identificador' => 'preg_comiteetica3_tieneconent',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual?',
                'identificador' => 'preg_comiteetica3_cuales_ent',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            
        ));
        $command->execute();
    }

}
