<?php

/**
 * Class ColocarDatosCommand
 * @author Me
 */
class ColocarDatosCommand extends CConsoleCommand
{
    public function run($args)
    {
        $usersSQL = "SELECT id FROM {{users}} WHERE username = :name";
        $builder = new CDbCommandBuilder(Yii::app()->db->schema);
        $idCommand = $builder->createSqlCommand($usersSQL,array(
            'name' => 'admin'
        ));
        list($idUser) = array_values($idCommand->queryRow()); //NOTE Importante
        $command = $builder->createMultipleInsertCommand("{{Tipoencuesta}}",array(
            array(
                'enunciado' => "Guión de entrevista para universidades, institutos tecnológicos, escuelas técnicas",
                'identificador' => 'tipoencuesta_uni',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => "Guión de entrevista para institutos, centros, grupos, laboratorios, otros",
                'identificador' => 'tipoencuesta_otros',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
        ));
        $command = $builder->createMultipleInsertCommand("{{Pregunta}}",array(
            //IMPORTANTE Grupo 1 de INSTRUMENTO IUTET
            array(
                'enunciado' => 'Nombre del entrevistado',
                'identificador' => 'preg_datos_nom_entr',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Universidades, institutos tecnológicos, escuelas técnicas',
                'identificador' => 'preg_datos_universidad_pertenece',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Año de fundación',
                'identificador' => 'preg_datos_ano_fundacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Ubicación',
                'identificador' => 'preg_datos_universidad_ubicacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Municipio',
                'identificador' => 'preg_datos_municipio',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Caracter',
                'identificador' => 'preg_datos_caracterpublicoprivado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            //FIN DE GRUPO 1
            //COMIENZO DE GRUPO 2
            array(
                'enunciado' => 'Número de nucleos y sedes',
                'identificador' => 'preg_sedenucleo_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Sede / Núcleo',
                'identificador' => 'preg_sedenucleo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Ubicación',
                'identificador' => 'preg_sedenucleo_ubicacion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            //FIN DE GRUPO 2
            //COMIENZO DE GRUPO 3 
            array(
                'enunciado' => 'Actividades de ciencia, tecnología e innovación que se desarrollan en  las universidades, institutos tecnológicos, escuelas técnicas, según el artículo 27 de la LOCTI',
                'identificador' => 'preg_actividadesciencia_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Si/No',
                'identificador' => 'preg_actividadesciencia_sino',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuales?',
                'identificador' => 'preg_actividadesciencia_cuales',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ), 
            // FIN DE GRUPO 3
            // COMIENZO DE GRUPO 4
            array(
                'enunciado' => 'Talento Humano en Ciencia, Tecnología e Innovación de la universidad/institutos tecnológicos/escuelas técnicas/otros',
                'identificador' => 'preg_talentohumano_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nombre',
                'identificador' => 'preg_talentohumano_nombre',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Edad',
                'identificador' => 'preg_talentohumano_edad',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nivel Académico',
                'identificador' => 'preg_talentohumano_nivelac',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Universidad en que cursó estudios',
                'identificador' => 'preg_talentohumano_uni_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nacional pública',
                'identificador' => 'preg_talentohumano_nacionalpub',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Nacional privada',
                'identificador' => 'preg_talentohumano_nacionalpri',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Internacional',
                'identificador' => 'preg_talentohumano_internacional',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ),        
            array(
                'enunciado' => 'Fuente de financiamiento de estudios',
                'identificador' => 'preg_talentohumano_fuentefin',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Categoría PEII',
                'identificador' => 'preg_talentohumano_categoriapeii',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Investigador',
                'identificador' => 'preg_talentohumano_pei_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Innovador',
                'identificador' => 'preg_talentohumano_pei_inn',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de Experiencia',
                'identificador' => 'preg_talentohumano_exp_area',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Linea de investigación',
                'identificador' => 'preg_talentohumano_linea_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ),
            //Fin del grupo  4
            //Comienzo del grupo 5
            array(
                'enunciado' => 'Numero de egresados de programas de doctorado en los últimos 12 años',
                'identificador' => 'preg_doctorado_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de doctorado existentes',
                'identificador' => 'preg_doctorado_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_doctorado_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 5
            //Comienzo del grupo 6
            array(
                'enunciado' => 'Numero de egresados de programas de maestria en los últimos 12 años',
                'identificador' => 'preg_maestria_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de maestria existentes',
                'identificador' => 'preg_maestria_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_maestria_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 6
            //Comienzo del grupo 7
            array(
                'enunciado' => 'Numero de egresados de programas de especialidades en los últimos 12 años',
                'identificador' => 'preg_especialidades_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de especialidades existentes',
                'identificador' => 'preg_especialidades_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_especialidades_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 7
            //Comienzo del grupo 8
            array(
                'enunciado' => 'Numero de egresados de programas de pregrado en los últimos 12 años',
                'identificador' => 'preg_pregrado_compuesta',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programas de pregrado existentes',
                'identificador' => 'preg_pregrado_existente',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'No',
                'identificador' => 'preg_pregrado_numero',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 8
            //Comienzo del grupo 9
            array(
                'enunciado' => 'Proyectos aprobados y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_proyectosaprob_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Proyectos aprobados y financiados',
                'identificador' => 'preg_proyectosaprob_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de proyectos aprobados',
                'identificador' => 'preg_proyectosaprob_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 9
            //Comienzo del grupo 10
            array(
                'enunciado' => 'Recursos aprobados y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_recursosaprob_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Recursos aprobados y financiados',
                'identificador' => 'preg_recursosaprob_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de recursos aprobados',
                'identificador' => 'preg_recursosaprob_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 10
            //Comienzo del grupo 11
            array(
                'enunciado' => 'Proyectos aprobados por área y financiados en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_proyectosaprob_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de concentración',
                'identificador' => 'preg_proyectosaprob_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Número de proyectos aprobados por área',
                'identificador' => 'preg_proyectosaprob_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 11
            //Comienzo del grupo 12
            array(
                'enunciado' => 'Recursos aprobados y financiados por área en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por entes de financiamiento',
                'identificador' => 'preg_recursosaprob_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de concentración',
                'identificador' => 'preg_recursosaprob_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Recursos aprobados',
                'identificador' => 'preg_recursosaprob_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 12
            //Comienzo del grupo 13
            array(
                'enunciado' => 'Producción Tecnológica (Patentes) en la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12 años por área de especialización',
                'identificador' => 'preg_patentes_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de especialización',
                'identificador' => 'preg_patentes_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Total de producción tecnológica (Patentes)',
                'identificador' => 'preg_patentes_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 13
            //Comienzo del grupo 14
            array(
                'enunciado' => 'Mencione patentes',
                'identificador' => 'preg_patentes_mencionar_pat',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ), 
            // Fin del grupo 14
            //Comienzo del grupo 15
            array(
                'enunciado' => 'Revistas arbitradas e indexadas y número de publicaciones por área de especialización que tienen  la universidad/institutos tecnológicos/escuelas técnicas/otros en los últimos 12',
                'identificador' => 'preg_revistas_area_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Area de especialización',
                'identificador' => 'preg_revistas_area_subq',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Revista',
                'identificador' => 'preg_revistas_area_revista',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Total de publicaciones',
                'identificador' => 'preg_revistas_area_num',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'ano',
                'compuesta' => true,
            ), 
            //Fin del grupo 15
            //Comienzo del grupo 16
            array(
                'enunciado' => 'Líneas de Investigación existentes en la universidad/institutos tecnológicos/escuelas técnicas/otros ',
                'identificador' => 'preg_lineas_inv_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Líneas de Investigación',
                'identificador' => 'preg_lineas_inv_lineasinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Ejes Temáticos',
                'identificador' => 'preg_lineas_inv_ejestematico',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Programa de Postgrado de adscripción',
                'identificador' => 'preg_lineas_inv_programapost',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            //Fin del grupo 16
            //Comienzo del grupo 17
            array(
                'enunciado' => 'Actores participantes en la ejecución de proyectos de ciencia y tecnología generados en la universidad/institutos tecnológicos/escuelas técnicas/otros',
                'identificador' => 'preg_actores_fin_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Actores participantes en la ejecución de proyectos',
                'identificador' => 'preg_actores_fin_actorespart',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Actores de financiamiento en la ejecución de proyectos',
                'identificador' => 'preg_actores_fin_actoresfin',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            // Fin del grupo 17
            //Comienzo del grupo 18
            array(
                'enunciado' => 'Pertenecen a alguna Red Temáticas de cooperación',
                'identificador' => 'preg_red_tem_pert',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Mencione',
                'identificador' => 'preg_red_tem_mencione',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            //Fin del grupo 18
            //Comienzo del grupo 19
            array(
                'enunciado' => 'Cuál es la problemática que se presenta en la universidad/institutos tecnológicos/escuelas técnicas/otros?',
                'identificador' => 'preg_problematica_cual',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Describa',
                'identificador' => 'preg_problematica_describa',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            // Fin del grupo 19
            // Comienzo del grupo 20
            array(
                'enunciado' => 'Infraestructura en ciencia, tecnología e innovación existente',
                'identificador' => 'preg_infraestructura_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Se encuentra Activa',
                'identificador' => 'preg_infraestructura_activa',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'checkbox',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Condiciones de espacios',
                'identificador' => 'preg_infraestructura_espacios',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Equipamiento',
                'identificador' => 'preg_infraestructura_equipamiento',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Uso de la infraestructura',
                'identificador' => 'preg_infraestructura_usoinf_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Docencia',
                'identificador' => 'preg_infraestructura_usodoc',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ), 
            array(
                'enunciado' => 'Investigacion',
                'identificador' => 'preg_infraestructura_usoinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            //Fin del grupo 20
            //Comienzo del grupo 21
            array(
                'enunciado' => '¿Actualmente tiene servicio de internet?',
                'identificador' => 'preg_internet_servint',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Proveedor de internet',
                'identificador' => 'preg_internet_proveedorint',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual proveedor?',
                'identificador' => 'preg_internet_cualprov',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Nivel de satisfacción del servicio?',
                'identificador' => 'preg_internet_usoinv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            // Fin del grupo 21
            // Comienzo grupo 22 
            array(
                'enunciado' => '¿Cuenta su Organización con un Comité de Ética qué evalúe, controle y conozca  los protocolos de investigación, experimentación y resultados que son presentados al público?',
                'identificador' => 'preg_comiteetica_evalue',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual comité?',
                'identificador' => 'preg_comiteetica_cual',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            // Fin del grupo 22
            // Comienzo del grupo 23
            array(
                'enunciado' =>'¿Cómo está compuesto? (para cada integrante, por favor señalar: Identificación, profesión, cargo, correo).?\n Nota: Si usted no tiene comité de Ética deje en blanco',
                'identificador' => 'preg_comiteetica2_composicion_comp',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'compuesta',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Identificación',
                'identificador' => 'preg_comiteetica2_ident',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Profesión',
                'identificador' => 'preg_comiteetica2_profesion',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Cargo',
                'identificador' => 'preg_comiteetica2_cargo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            array(
                'enunciado' => 'Correo',
                'identificador' => 'preg_comiteetica2_correo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => true,
            ),
            // Fin del grupo 23
            // Comienzo del grupo 24 
            array(
                'enunciado' => '¿En qué fecha y a través de qué resolución (administrativa, legal) fue creado?',
                'identificador' => 'preg_comiteetica3_fecha',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Dispone de actas de las reuniones que realiza?',
                'identificador' => 'preg_comiteetica3_reuniones',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuántos trabajos científicos han evaluado en los últimos cinco años?',
                'identificador' => 'preg_comiteetica3_trabev',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'number',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Mencione titulos por favor',
                'identificador' => 'preg_comiteetica3_titulosmenc',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'tag-input',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cuáles han sido las principales dificultades que ha encontrado en su funcionamiento?',
                'identificador' => 'preg_comiteetica3_principalesdif',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => 'Si no dispone de un Comité de Ética, ¿de qué forma se evalúa y/o controla las investigaciones, proyectos?',
                'identificador' => 'preg_comiteetica3_formaev',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'text',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Tiene conocimiento y vínculos con otras entidades que evalúen éticamente investigaciones científicas (Universidades, Comités de Ética autónomos, instituciones públicas y/o privadas de financiamiento de proyectos, etc.)?.',
                'identificador' => 'preg_comiteetica3_tieneconent',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            array(
                'enunciado' => '¿Cual?',
                'identificador' => 'preg_comiteetica3_cuales_ent',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
                'tipo' => 'list',
                'compuesta' => false,
            ),
            
        ));
        $command->execute();
        /**
         * Fin de preguntas
         */
        $command = $builder->createMultipleInsertCommand("{{Grupo}}",array(
            array(
                'enunciado' => 'Identificación',
                'identificador' => 'datos',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Núcleos y sedes',
                'identificador' => 'sedenucleo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Actividades de ciencia y tecnología desarrolladas',
                'identificador' => 'actividadesciencia',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Talento Humano',
                'identificador' => 'talentohumano',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de doctorado',
                'identificador' => 'doctorado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de maestría',
                'identificador' => 'maestria',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de especialidades',
                'identificador' => 'especialidades',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ), 
            array(
                'enunciado' => 'Programas de pregrado',
                'identificador' => 'pregrado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Proyectos aprobados',
                'identificador' => 'proyectosaprob',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Recursos aprobados en la universidad',
                'identificador' => 'recursosaprob',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Proyectos aprobados por area',
                'identificador' =>'proyectosaprob_area',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Recursos aprobados por area',
                'identificador' => 'recursosaprob_area',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Patentes aprobadas',
                'identificador' => 'patentes',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Lista de patentes',
                'identificador' => 'patentes2',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Revistas arbitradas e indexadas',
                'identificador' => 'revistas',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Lineas de investigación',
                'identificador' => 'lineas_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Actores participantes en la ejecución de proyectos',
                'identificador' => 'actores',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Redes temáticas',
                'identificador' => 'red_tem',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Problemáticas',
                'identificador' => 'problematica',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Infraestructura',
                'identificador' => 'infraestructura',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Uso de internet',
                'identificador' => 'internet',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Comité de ética',
                'identificador' => 'comiteetica',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Comité de ética',
                'identificador' => 'comiteetica2',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Comité de ética',
                'identificador' => 'comiteetica3',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
        ));
        $command->execute();

        $command = $builder->createMultipleInsertCommand("{{Grupocomp}}",array(
            array(
                'enunciado' => 'Núcleos y sedes',
                'identificador' => 'sedenucleo',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Talento Humano',
                'identificador' => 'talentohumano',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de doctorado',
                'identificador' => 'doctorado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de maestría',
                'identificador' => 'maestria',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de especialidades',
                'identificador' => 'especialidades',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Programas de pregrado',
                'identificador' => 'pregrado',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Proyectos aprobados para la universidad',
                'identificador' => 'proyectosaprob',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Recursos aprobados por la universidad',
                'identificador' => 'recursossaprob',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Patentes aprobadas',
                'identificador' => 'patentes',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Lineas de investigación',
                'identificador' => 'lineas_inv',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Actores de financiamiento',
                'identificador' => 'actores_fin',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Redes temáticas',
                'identificador' => 'red_tem',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Problemáticas enfrentadas',
                'identificador' => 'problematica',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Infraestructura',
                'identificador' => 'infraestructura',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),
            array(
                'enunciado' => 'Comité de Ética',
                'identificador' => 'comiteetica2',
                'creado_en' => new CDbExpression('NOW()'),
                'actualizado_en' => new CDbExpression('NOW()'),
                'user_id' => $idUser,
            ),

        ));

        // Comenzamos a insertar pregunta grupo
        $sqlPreguntaGrupo = "INSERT INTO {{PreguntaGrupo}} (pregunta_id, grupo_id, peso) (SELECT p.id AS pregunta_id, g.id AS grupo_id, :peso AS peso FROM {{Pregunta}} p JOIN {{Grupo}} g ON g.identificador=:grupoid WHERE p.identificador =:preguntaid)";
        $commandPreguntaGrupo = Yii::app()->db->createCommand($sqlPreguntaGrupo);
        $commandPreguntaGrupo->bindValue(':grupoid','sedenucleo');
        $commandPreguntaGrupo->bindValue(':preguntaid','preg_sedenucleo');
        $commandPreguntaGrupo->bindValue(':peso','1');
        //TODO Pasar lo de los parametros a las consultas
        //NOTE: Todos los arrays están ordenados por peso.
        $arrayPreguntaGrupo = array(
            'datos' => array(
                'preg_datos_nom_entr',
                'preg_datos_universidad_pertenece',
                'preg_datos_ano_fundacion',
                'preg_datos_universidad_ubicacion',
                'preg_datos_municipio',
                'preg_datos_caracterpublicoprivado',
            ),
            'sedenucleo' => array(
                'preg_sedenucleo_compuesta',
                'preg_sedenucleo',
                'preg_sedenucleo_ubicacion',
            ),
            'actividadesciencia' => array(
                'preg_actividadesciencia_compuesta',
                'preg_actividadesciencia_sino',
                'preg_actividadesciencia_cuales',
            ),
            'talentohumano' => array(
                'preg_talentohumano_compuesta',
                'preg_talentohumano_nombre',
                'preg_talentohumano_edad',
                'preg_talentohumano_nivelac',
                'preg_talentohumano_uni_compuesta',
                'preg_talentohumano_nacionalpub',
                'preg_talentohumano_nacionalpri',
                'preg_talentohumano_internacional',
                'preg_talentohumano_fuentefin',
                'preg_talentohumano_categoriapeii',
                'preg_talentohumano_pei_inv',
                'preg_talentohumano_pei_inn',
                'preg_talentohumano_exp_area',
                'preg_talentohumano_linea_inv',
            ),
            'doctorado' => array(
                'preg_doctorado_compuesta',
                'preg_doctorado_existente',
                'preg_doctorado_numero',
            ),
            'maestria' => array(
                'preg_maestria_compuesta',
                'preg_maestria_existente',
                'preg_maestria_numero',
            ),
            'especialidades' => array(
                'preg_especialidades_compuesta',
                'preg_especialidades_existente',
                'preg_especialidades_numero',
            ),
            'pregrado' => array(
                'preg_pregrado_compuesta',
                'preg_pregrado_existente',
                'preg_pregrado_numero',
            ),
            'proyectosaprob' => array(
                'preg_proyectosaprob_comp',
                'preg_proyectosaprob_subq',
                'preg_proyectosaprob_num',
            ),
            'recursosaprob' => array(
                'preg_recursosaprob_comp',
                'preg_recursosaprob_subq',
                'preg_recursosaprob_num',
            ),
            'proyectosaprob_area' => array(
                'preg_proyectosaprob_area_comp',
                'preg_proyectosaprob_area_subq',
                'preg_proyectosaprob_area_num',
            ),
            'patentes' => array(
                'preg_patentes_area_comp',
                'preg_patentes_area_subq',
                'preg_patentes_area_num',
            ),
            'patentes2' => array(
                'preg_patentes_mencionar_pat',
            ),
            'recursosaprob_area' => array(
                'preg_recursosaprob_area_comp',
                'preg_recursosaprob_area_subq',
                'preg_recursosaprob_area_num',
            ),
            'revistas' => array(
                'preg_revistas_area_comp',
                'preg_revistas_area_subq',
                'preg_revistas_area_revista',
                'preg_revistas_area_num',
            ),
            'lineas_inv' => array(
                'preg_lineas_inv_comp',
                'preg_lineas_inv_lineasinv',
                'preg_lineas_inv_ejestematico',
                'preg_lineas_inv_programapost',
            ),
            'actores' => array(
                'preg_actores_fin_comp',
                'preg_actores_fin_actorespart',
                'preg_actores_fin_actoresfin',
            ),
            'red_tem' => array(
                'preg_red_tem_pert',
                'preg_red_tem_mencione',
            ),
            'problematica' => array(
                'preg_problematica_cual',
                'preg_problematica_describa',
            ),
            'infraestructura' => array(
                'preg_infraestructura_comp',
                'preg_infraestructura_activa',
                'preg_infraestructura_espacios',
                'preg_infraestructura_equipamiento',
                'preg_infraestructura_usoinf_comp',
                'preg_infraestructura_usodoc',
                'preg_infraestructura_usoinv',
            ),
            'internet' => array(
                'preg_internet_servint',
                'preg_internet_proveedorint',
                'preg_internet_cualprov',
                'preg_internet_usoinv',
            ),
            'comiteetica' => array(
                'preg_comiteetica_evalue',
                'preg_comiteetica_cual',
            ),
            'comiteetica2' => array(
                'preg_comiteetica2_composicion_comp',
                'preg_comiteetica2_ident',
                'preg_comiteetica2_profesion',
                'preg_comiteetica2_cargo',
                'preg_comiteetica2_correo',
            ),
            'comiteetica3' => array(
                'preg_comiteetica3_fecha',
                'preg_comiteetica3_reuniones',
                'preg_comiteetica3_trabev',
                'preg_comiteetica3_titulosmenc',
                'preg_comiteetica3_principalesdif',
                'preg_comiteetica3_formaev',
                'preg_comiteetica3_tieneconent',
                'preg_comiteetica3_cuales_ent',
            ),
        );

        foreach ($arrayPreguntaGrupo as $idGrupo=>$grupoPreguntas) {
            foreach ($grupoPreguntas as $i=>$pregunta) {  
                $commandPreguntaGrupo->bindValue(':grupoid',$idGrupo);
                $commandPreguntaGrupo->bindValue(':preguntaid',$pregunta);
                $commandPreguntaGrupo->bindValue(':peso',$i);
                echo "Comando con pregunta ($idGrupo,$pregunta) y peso $i ejecutado\n";
                $commandPreguntaGrupo->execute();
            }
        }
        //Comenzamos con Grupotipoencuesta 
        $sqlEncuestaGrupo = "INSERT INTO {{TipoencuestaGrupo}} (tipoencuesta_id, grupo_id, peso) (SELECT t.id AS tipoencuesta_id, g.id AS grupo_id, :peso AS peso FROM {{Tipoencuesta}} t JOIN {{Grupo}} g ON g.identificador=:grupoid WHERE t.identificador =:tipoencuestaid)";
        $arrayEncuestaGrupo = array(
            'tipoencuesta_uni' => array(
                'datos',
                'sedenucleo',
                'actividadesciencia',
                'talentohumano',
                'doctorado',
                'maestria',
                'especialidades',
                'pregrado',
                'proyectosaprob',
                'recursosaprob',
                'proyectosaprob_area',
                'recursosaprob_area',
                'patentes',
                'patentes2',
                'revistas',
                'lineas_inv',
                'actores',
                'red_tem',
                'problematica',
                'infraestructura',
                'internet',
                'comiteetica',
                'comiteetica2',
                'comiteetica3',
            ),
        );
        $commandTipoEncuestaGrupo = Yii::app()->db->createCommand($sqlEncuestaGrupo);
        foreach ($arrayEncuestaGrupo as $idEncuesta=>$grupos) {
            foreach ($grupos as $i=>$grupo) {  
                $commandTipoEncuestaGrupo->bindValue(':grupoid',$grupo);
                $commandTipoEncuestaGrupo->bindValue(':tipoencuestaid',$idEncuesta);
                $commandTipoEncuestaGrupo->bindValue(':peso',$i);
                echo "Comando con Grupo ($idEncuesta,$grupo) y peso $i ejecutado\n";
                $commandTipoEncuestaGrupo->execute();
            }
        }
    }

}
